apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: launchpad-seaweedfs-operator-permissions
  labels:
    app.kubernetes.io/managed-by: rocketchat-launchpad
rules:
- apiGroups:
  - seaweed.seaweedfs.com
  resources:
  - seaweeds/finalizers
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
