apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: helm-controller
  annotations:
    launchpad-registry-overwrite-traefik: "image.registry:(registry)"
    launchpad-registry-overwrite-traefik-repo: "image.repository:library/traefik"

    launchpad-registry-overwrite-imagePullSecrets-deployment: "deployment.imagePullSecrets[].name:launchpad-registry-credentials"
spec:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  version: 37.0.0
  targetNamespace: traefik
  createNamespace: true
  valuesContent: |-
    deployment:
      replicas: 2
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
    - "--api.insecure=false"
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    metrics:
      prometheus:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
