apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: monitoring-sc
provisioner: driver.longhorn.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  fsType: xfs
