apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mongodb-operator
  namespace: helm-controller
spec:
  repo: https://mongodb.github.io/helm-charts/
  chart: mongodb-kubernetes
  version: v1.6.1
  targetNamespace: mongodb
  createNamespace: true
  #valuesContent: |-
