apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: xfs
  type: gp3 # io2
  encrypted: "true"
